[workspace]
resolver = "2"
members = [
    "packages/rs-ultrahonk-verifier",
    "contracts/rs-soroban-ultrahonk",
    "contracts/tornado-classic/contracts",
]
[workspace.dependencies]
soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk", rev="3b031847eb043856cc5bcad45bd5a6512370cd16", default-features = false }

[profile.release]
opt-level = "z"
overflow-checks = true
lto = true
codegen-units = 1
panic = "abort"
strip = true
